---
title: "Learn to Code with Javascript: Strings"
type: "article"  # challenge, exercise, article, video
description: "Learn about the String data type in JavaScript."
tags: "javascript, strings"
ignore:
- "learn-to-code-with-javascript-strings.md"
