---
title: "Learn to Code with JavaScript: Arrays"
type: "article"  # challenge, exercise, article, video
description: "Learn about the Array data structure in JavaScript."
tags: "javascript, arrays"
ignore:
- "learn-to-code-with-javascript-arrays.md"
