---
title: "Learn to Code with JavaScript: Loops"
type: "article"  # challenge, exercise, article, video
description: "Learn how to create code that repeats itself."
tags: "javascript, loops"
ignore:
- "learn-to-code-with-javascript-loops.md"
