---
title: "Learn to Code with Javascript: Boolean and Conditional Statements"
type: "article"  # challenge, exercise, article, video
description: "Learn how to make decisions with code."
tags: "javascript, booleans, conditionals"
ignore:
- "learn-to-code-with-javascript-boolean-and-conditional-statements.md"
