---
title: "Learn to Code with JavaScript: Functions"
type: "article"  # challenge, exercise, article, video
description: "Promote code reuse by defining functions."
tags: "javascript, functions"
ignore:
- "learn-to-code-with-javascript-functions.md"
