---
title: "Learn to Code with JavaScript: DOM Manipulation and Events"
type: "article"  # challenge, exercise, article, video
description: "Learn how to respond to user actions and update a webpage."
tags: "javascript, dom, events"
ignore:
- "learn-to-code-with-javascript-dom-manipulation-and-events.md"
